{%set name = "cliff" %}
{%set version = "2.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a12a6bd3cf9085f0e0589c5019037ac4ee410413abbb76189fa62695f79f84fc

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools
    - pbr >=1.6

  run:
    - python
    - cmd2 >=0.6.7
    - prettytable <0.8,>=0.7
    - pyparsing >=2.0.1
    - six >=1.9.0
    - stevedore >=1.10.0
    - unicodecsv >=0.8.0  # [not py3k]
    - pyyaml >=3.1.0

test:
  imports:
    - cliff
    - cliff.app
    - cliff.commandmanager
    - cliff.command
    - cliff.interactive

about:
  home: https://github.com/openstack/cliff
  license: Apache 2.0
  license_family: Apache
  summary: 'Command Line Interface Formulation Framework'
  dev_url: http://git.openstack.org/cgit/openstack/cliff
  doc_url: http://docs.openstack.org/developer/cliff

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
