travis:
  secure:
    BINSTAR_TOKEN: bup1KhNPFqEyeZZH35nAGInjh6mrmLuFaB9QUVaUkrQkHAzgOehsk2F2QRyYwGZQz+y31xDAqXgKIzeiSfQRFQyvzVSCAlg7jgpoUbR2QOs7Ye4a7cxxO1osEWsR8FXrGQuBvW/IfR50t+xe06ztx9YAMOaI1DatXogKRPHUemsUQPhGMdkNscl6c6FxTvuHawStGFBieniqbe/6YpCOzEh6ztpVspBSxg85RVQzfNZ+WPDYIKWVKV6Xpi2Q/cfkXcSECTOfbkmnBg2O9wQ3Uk+NQ3e5YQEnxH2TvpivA+f6Dt/QvL19UzucoNx1fJKAgdDIMkzvsrT1FfFI0HNUhjvq+r8gz2sKc0/axWCOXfstcER5BOndBRQUrPXbv1zlmaEQzXzrLjUmLRmTDXYDqssgZK4eGA2mtajO/83XfpKAg9/WQHE9zzn/X6vqRAkey7R30Q12VILFsONBo3YWv8kFIXpZKEhbLC8VcHC1yVpshWQ4CAyl3H9NcTggrlK9Q6Fl2pwJKgQlG2X9trLhMQl0z+GbFcU1x4+jCq2/WTNrssk6foVEWmnRb5Q1OImb6Q9wCXmZ9Z5getWShb3WRQO9fZWH/UdL1R6ydMMtUiJpjIk3c4mPXraLdbMDND8FVIG7Jn2SHk6Ow83KcVPu6Y3v+gU2adl/wRWn42oNfU8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
